import requests

url = 'https://www.jianshu.com/search/do?q=go&type=note&page=1&order_by=default'
headers = {
    "user-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
}
# response = requests.post(url=url,headers=headers)

# print(response.content.decode('utf8'))

res = {"q": "go", "page": 1, "type": "note", "total_count": 10000, "per_page": 10, "total_pages": 100,
       "order_by": "default", "entries": [{"id": 82731535,
                                           "title": "<em class='search-result-highlight'>GO</em> 微服务<em class='search-result-highlight'>GO</em>-Micro -（5）来自<em class='search-result-highlight'>GO</em> 夜读 关于<em class='search-result-highlight'>Go</em>-Micro （第一期）学习笔记",
                                           "slug": "bd0d2f25dabb",
                                           "content": "……来自<em class='search-result-highlight'>GO</em> 夜读 学习笔记 学习来源：https://www.bilibili.com/video/BV18E411o7c5?……框架模块 （5）关于<em class='search-result-highlight'>GO</em>-Micro  基础组件调用关系 流程说明： 每一个Service服务都有一个Cilent 和Server <em class='search-result-highlight'>go</em>-micro中服务发现和注册： （6）关于<em class='search-result-highlight'>GO</em>-Micro 其他组件……（10）关于<em class='search-result-highlight'>GO</em>-Micro 中的插件化……",
                                           "user": {"id": 1789550, "nickname": "小钟钟同学", "slug": "d6960089b087",
                                                    "avatar_url": "https://upload.jianshu.io/users/upload_avatars/1789550/408759869e86"},
                                           "notebook": {"id": 49172498, "name": "GO Micro 微服务系列"}, "commentable": True,
                                           "public_comments_count": 0, "likes_count": 1, "views_count": 586,
                                           "total_rewards_count": 0, "first_shared_at": "2021-01-18T07:30:37.000Z"},
                                          {"id": 92891826,
                                           "title": "Mac 中 <em class='search-result-highlight'>go</em> get 报错 compile: version \"<em class='search-result-highlight'>go</em>1.16\" does not match <em class='search-result-highlight'>go</em> tool version \"<em class='search-result-highlight'>go</em>1.16.3\"",
                                           "slug": "711fadcf8e32",
                                           "content": "……报错信息如下 原因分析 我们在系统中 有多个 <em class='search-result-highlight'>go</em> 环境造成的； 如果是通过  brew install <em class='search-result-highlight'>go</em> 的方式安装的 <em class='search-result-highlight'>go</em>环境【1.16.3】；那么，<em class='search-result-highlight'>go</em>的环境会默认安装在路径如下 /usr/local……/Cellar 这就成就了  <em class='search-result-highlight'>go</em>1.16.3 的环境 如果是通过下载安装包的方式安装的 <em class='search-result-highlight'>go</em> 环境【1.16】；那么，<em class='search-result-highlight'>go</em>的默认安装路径如下 /usr/local/<em class='search-result-highlight'>go</em> 而我们系统PATH中配置 <em class='search-result-highlight'>go</em>……的环境假设在  /usr/local/bin 下 系统再编译<em class='search-result-highlight'>go</em>的时候，系统调用的应该是【 /usr/local/<em class='search-result-highlight'>go</em>/bin 下面的 1.16 环境】，<em class='search-result-highlight'>go</em> tool 中使用的 应该是 【/usr/local……",
                                           "user": {"id": 8579438, "nickname": "PHP的点滴", "slug": "6f3de36309a9",
                                                    "avatar_url": "https://upload.jianshu.io/users/upload_avatars/8579438/c5bc1cc4-bcb5-4b95-bb70-791113aec040.jpeg"},
                                           "notebook": {"id": 49698312, "name": "ELK"}, "commentable": True,
                                           "public_comments_count": 0, "likes_count": 0, "views_count": 992,
                                           "total_rewards_count": 0, "first_shared_at": "2021-09-15T10:07:15.000Z"},
                                          {"id": 59000387,
                                           "title": "<em class='search-result-highlight'>go</em>的三个运行基本命令的区别，<em class='search-result-highlight'>go</em> run ,<em class='search-result-highlight'>go</em> build 和 <em class='search-result-highlight'>go</em> install",
                                           "slug": "b143f84cc694",
                                           "content": "……最近在自学<em class='search-result-highlight'>go</em>，遇到点基础的问题，通过自己实际操作之后得出结论 在实际操作之前，我们需要知道<em class='search-result-highlight'>go</em>有三种源码文件：    1，命令源码文件；声明自己属于main包，并且包含main函数的文件，每个项目只能有一个这样的文件……<em class='search-result-highlight'>go</em> run : 编译并直接运行程序，不产生可执行文件，只产生临时文件，方便用户调试（即在bin目录和pkg目录不产生任何文件）,其后只能+命令源码文件。……好了，<em class='search-result-highlight'>go</em> run , <em class='search-result-highlight'>go</em> build 和 <em class='search-result-highlight'>go</em> install三者的区别就到这里了。……",
                                           "user": {"id": 19560490, "nickname": "Newzer", "slug": "c9f80503dfa2",
                                                    "avatar_url": "https://upload.jianshu.io/users/upload_avatars/19560490/c8d56c38-2455-4b1f-97bd-0a7b8de1b62c"},
                                           "notebook": {"id": 41205435, "name": "技术"}, "commentable": True,
                                           "public_comments_count": 0, "likes_count": 3, "views_count": 2617,
                                           "total_rewards_count": 0, "first_shared_at": "2020-01-17T02:33:08.000Z"},
                                          {"id": 37798637,
                                           "title": "To <em class='search-result-highlight'>Go</em> Fast, <em class='search-result-highlight'>Go</em> Alone – To <em class='search-result-highlight'>Go</em> Far, <em class='search-result-highlight'>Go</em> Together: Lifestyle Practice",
                                           "slug": "00e0f466d749",
                                           "content": "……It’s said that if you want to <em class='search-result-highlight'>go</em> fast, <em class='search-result-highlight'>go</em> alone. If you want to <em class='search-result-highlight'>go</em> far, <em class='search-result-highlight'>go</em> together.……You are the beginning and end of any consideration about how things <em class='search-result-highlight'>go</em>.……But then there’s that “<em class='search-result-highlight'>go</em> far” part.……",
                                           "user": {"id": 12873414, "nickname": "愚乐小白", "slug": "f0a0ef3109d5",
                                                    "avatar_url": "https://upload.jianshu.io/users/upload_avatars/12873414/cbec3e82-90b2-478a-8d24-e4b7adfbf225"},
                                           "notebook": {"id": 26970331, "name": "日志007"}, "commentable": True,
                                           "public_comments_count": 1, "likes_count": 1, "views_count": 393,
                                           "total_rewards_count": 0, "first_shared_at": "2018-12-04T15:45:56.000Z"},
                                          {"id": 82653524,
                                           "title": "<em class='search-result-highlight'>GO</em> 微服务<em class='search-result-highlight'>GO</em>-Micro -（4）Micro和<em class='search-result-highlight'>GO</em>-Micro",
                                           "slug": "a92ece51e2d6",
                                           "content": "……] 用来扩展工具 <em class='search-result-highlight'>GO</em>-Micro 官网信息介绍 来自官方文档的介绍（手打主要是为了方便自己理解） 1.介绍 <em class='search-result-highlight'>go</em>语言的插件化的基础微服务框架 提升开发效率 提供一套微服务的架构,部分微服务工具的集合……<em class='search-result-highlight'>Go</em> Mirco 核心模块设计解析 框架 - 使用 <em class='search-result-highlight'>go</em>-micro[https://micro.mu/framework.html] 编写微服务的 <em class='search-result-highlight'>Go</em> 框架；服务发现，远程过程调用，发布 / 订阅等……Codec：<em class='search-result-highlight'>go</em>-micro中数据传输过程中的编码和解码接口。<em class='search-result-highlight'>go</em>-micro中有多重编码方式，默认的实现方式是protobuf，除此之外，还有json等格式。……",
                                           "user": {"id": 1789550, "nickname": "小钟钟同学", "slug": "d6960089b087",
                                                    "avatar_url": "https://upload.jianshu.io/users/upload_avatars/1789550/408759869e86"},
                                           "notebook": {"id": 49172498, "name": "GO Micro 微服务系列"}, "commentable": True,
                                           "public_comments_count": 0, "likes_count": 0, "views_count": 1707,
                                           "total_rewards_count": 0, "first_shared_at": "2021-01-18T05:13:42.000Z"},
                                          {"id": 77339521,
                                           "title": "<em class='search-result-highlight'>Go</em> | <em class='search-result-highlight'>Go</em> 语言打包静态文件以及如何与Gin一起使用<em class='search-result-highlight'>Go</em>-bindata",
                                           "slug": "a7f5885679ef",
                                           "content": "……<em class='search-result-highlight'>Go</em> | <em class='search-result-highlight'>Go</em> 语言打包静态文件以及如何与Gin一起使用<em class='search-result-highlight'>Go</em>-bindata 系列文章目录 第一章 <em class='search-result-highlight'>Go</em> 语言打包静态文件以及如何与Gin一起使用<em class='search-result-highlight'>Go</em>-bindata Table of Contents……安装 <em class='search-result-highlight'>go</em>-bindata-assetfs 这个需要和 <em class='search-result-highlight'>go</em>-bindata 一起安装，如果已经安装了  <em class='search-result-highlight'>go</em>-bindata  则不需要再次安装 3.……/jteeuwen/<em class='search-result-highlight'>go</em>-bindata https://github.com/elazarl/<em class='search-result-highlight'>go</em>-bindata-assetfs https://github.com/<em class='search-result-highlight'>go</em>-bindata/<em class='search-result-highlight'>go</em>-bindata……",
                                           "user": {"id": 11674949, "nickname": "双鬼带单", "slug": "93bbc5742a4e",
                                                    "avatar_url": "https://upload.jianshu.io/users/upload_avatars/11674949/980b28b7-5e7e-4be7-9b55-5991d93df590"},
                                           "notebook": {"id": 47862981, "name": "Go"}, "commentable": True,
                                           "public_comments_count": 0, "likes_count": 2, "views_count": 1422,
                                           "total_rewards_count": 0, "first_shared_at": "2020-09-16T14:52:42.000Z"},
                                          {"id": 41133911,
                                           "title": "咬文嚼字823《<em class='search-result-highlight'>Go</em>: <em class='search-result-highlight'>go</em>，<em class='search-result-highlight'>go</em>，let’s  <em class='search-result-highlight'>go</em>》",
                                           "slug": "6ef9e6d759ad",
                                           "content": "……【字句】<em class='search-result-highlight'>Go</em>，let’s <em class='search-result-highlight'>go</em>！Let’s <em class='search-result-highlight'>go</em> home！ 【行文】准备写英文？怎么可能呢？如果选择英文行文那就坏事，要进修五年，何必还花这个冤枉钱去读书，想想可以的！……",
                                           "user": {"id": 6624607, "nickname": "老区游子", "slug": "de7b52561e3e",
                                                    "avatar_url": "https://upload.jianshu.io/users/upload_avatars/6624607/8da61380-4554-4738-8285-ad0da1e380b3.jpg"},
                                           "notebook": {"id": 13797679, "name": "日记本"}, "commentable": True,
                                           "public_comments_count": 0, "likes_count": 4, "views_count": 639,
                                           "total_rewards_count": 0, "first_shared_at": "2019-02-09T21:56:46.000Z"},
                                          {"id": 57654391,
                                           "title": "<em class='search-result-highlight'>Go</em> 语言圣经-习题汇总（<em class='search-result-highlight'>Go</em> 程序设计语言/The <em class='search-result-highlight'>Go</em> Programming Language）",
                                           "slug": "a2065fe7c39b",
                                           "content": "……本文针对 <em class='search-result-highlight'>Go</em> 语言圣经 - 《<em class='search-result-highlight'>Go</em> 程序设计语言/The <em class='search-result-highlight'>Go</em> Programming Language》的所有习题进行筛选去重后，选取了一些比较典型的案例（80%以上）进行解析解答，分为两个版本，分别适合有原书和没有原书的童鞋进行学习巩固……] 读书笔记，欢迎收录[https://github.com/a1029563229/The-<em class='search-result-highlight'>Go</em>-Programming-Language] <em class='search-result-highlight'>Go</em> 学习笔记，欢迎收录[https://github.com……/a1029563229/<em class='search-result-highlight'>go</em>-excerpt]……",
                                           "user": {"id": 6218078, "nickname": "昵称不用太拉风", "slug": "318281a067b7",
                                                    "avatar_url": "https://upload.jianshu.io/users/upload_avatars/6218078/9850d032-d550-4ad1-9465-2c483dd6929a.jpg"},
                                           "notebook": {"id": 40430923, "name": "技术文章"}, "commentable": True,
                                           "public_comments_count": 2, "likes_count": 0, "views_count": 2249,
                                           "total_rewards_count": 0, "first_shared_at": "2019-12-14T02:00:49.000Z"},
                                          {"id": 44025682,
                                           "title": "程序员：没用过<em class='search-result-highlight'>go</em>，入职直接让写<em class='search-result-highlight'>go</em>，网友：<em class='search-result-highlight'>go</em>是拿来就能用的语言",
                                           "slug": "5a6d780fd8cd",
                                           "content": "……请输入图片描述 程序员：没用过<em class='search-result-highlight'>go</em>，入职直接让写<em class='search-result-highlight'>go</em>，网友：<em class='search-result-highlight'>go</em>是拿来就能用的语言 最近就有一个程序员网友面临了这样一个问题，这位网友之前并没有接触过<em class='search-result-highlight'>go</em>语言，可是入职后就要求他写<em class='search-result-highlight'>go</em>代码，他现在在公司里是一边熟悉公司各种环境……请输入图片描述 程序员：没用过<em class='search-result-highlight'>go</em>，入职直接让写<em class='search-result-highlight'>go</em>，网友：<em class='search-result-highlight'>go</em>是拿来就能用的语言 网友一：<em class='search-result-highlight'>go</em>就是拿来就能用的语言 作者点评：拿来就用对一些人来说真是这样，前提是需要有其他计算机语言的基础，只有这个基础在那摆着……网友八：我这样的小测试都在学习<em class='search-result-highlight'>go</em> 使用<em class='search-result-highlight'>go</em>，还能帮到点自己的工作内容 作者点评：测试同学都可以写<em class='search-result-highlight'>go</em>，可见<em class='search-result-highlight'>go</em>语言并不复杂，何况是一个有计算机语言基础的程序员呢。……",
                                           "user": {"id": 16823857, "nickname": "IT星辰", "slug": "81f9f04977ed",
                                                    "avatar_url": "https://cdn2.jianshu.io/assets/default_avatar/4-3397163ecdb3855a0a4139c34a695885.jpg"},
                                           "notebook": {"id": 35158109, "name": "日记本"}, "commentable": True,
                                           "public_comments_count": 0, "likes_count": 0, "views_count": 791,
                                           "total_rewards_count": 0, "first_shared_at": "2019-03-29T12:52:57.000Z"},
                                          {"id": 25701002,
                                           "title": "<em class='search-result-highlight'>Go</em>学习笔记（一）什么是<em class='search-result-highlight'>Go</em>，如何准备<em class='search-result-highlight'>Go</em>开发环境",
                                           "slug": "8b8d8ace3ee2",
                                           "content": "……<em class='search-result-highlight'>Go</em>的官方网站https://golang.org/说<em class='search-result-highlight'>Go</em>是一种开源的编程语言，它能够轻松的构建出简单、可信以及高效的软件。……在我设置的<em class='search-result-highlight'>Go</em>的工作路径下创建src/hello文件夹，然后在这个文件夹下创建hello.<em class='search-result-highlight'>go</em>，用Notepad++编辑，添加如下代码 随后是编译环节，从CMD中进入源代码所在路径, 运行 <em class='search-result-highlight'>go</em> build……到目前为止环境是准备好了，倒是具体语法还没有开始学，不过我找到了一些资源，用于后面学习 无闻的《<em class='search-result-highlight'>Go</em> 编程基础》 <em class='search-result-highlight'>Go</em>语言中文社区 <em class='search-result-highlight'>Go</em>语言之旅 雨痕开源的<em class='search-result-highlight'>Go</em>学习笔记 <em class='search-result-highlight'>go</em> web 编程……",
                                           "user": {"id": 2013053, "nickname": "xuzhougeng", "slug": "9ea40b5f607a",
                                                    "avatar_url": "https://upload.jianshu.io/users/upload_avatars/2013053/1891bcc4-f17f-4ef9-a835-d5daa9ddc4b2.png"},
                                           "notebook": {"id": 19854283, "name": "编程语言学习笔记"}, "commentable": True,
                                           "public_comments_count": 3, "likes_count": 8, "views_count": 1036,
                                           "total_rewards_count": 0, "first_shared_at": "2018-03-26T06:42:35.000Z"}],
       "related_users": [{"id": 3847153,
                          "avatar_url": "https://cdn2.jianshu.io/assets/default_avatar/3-9a2bcc21a5d89e21dafc73b39dc5f582.jpg",
                          "nickname": "kein_go_go_go", "slug": "d2e24e2d5529", "total_wordage": 968,
                          "total_likes_count": 1}, {"id": 1900881,
                                                    "avatar_url": "https://cdn2.jianshu.io/assets/default_avatar/12-aeeea4bedf10f2a12c0d50d626951489.jpg",
                                                    "nickname": "Alice_Go_Go_Go", "slug": "949943bd92cb",
                                                    "total_wordage": 2716, "total_likes_count": 7}, {"id": 19912699,
                                                                                                     "avatar_url": "https://cdn2.jianshu.io/assets/default_avatar/11-4d7c6ca89f439111aff57b23be1c73ba.jpg",
                                                                                                     "nickname": "go1go",
                                                                                                     "slug": "db934850f3dc",
                                                                                                     "total_wordage": 2919,
                                                                                                     "total_likes_count": 0}],
       "more_related_users": True, "related_collections": [{"id": 37379, "title": "技术干货", "slug": "38d96caffb2f",
                                                            "image_url": "https://upload.jianshu.io/collections/images/37379/android.graphics.Bitmap_5be8d38.jpeg",
                                                            "public_notes_count": 7130, "likes_count": 19229},
                                                           {"id": 294449, "title": "PHP经验分享", "slug": "5b1d36fefe6a",
                                                            "image_url": "https://upload.jianshu.io/collections/images/294449/a2696cd8a118efbace335aca23a91da3.jpg",
                                                            "public_notes_count": 2001, "likes_count": 2650},
                                                           {"id": 1729948, "title": "生信分析流程", "slug": "14abacc0940e",
                                                            "image_url": "https://upload.jianshu.io/collections/images/1729948/%E7%94%9F%E4%BF%A1%E6%B5%81%E7%A8%8B.png",
                                                            "public_notes_count": 204, "likes_count": 2113}],
       "more_related_collections": True}
entrieslist = res['entries']
for item in entrieslist:
    articleUrl = 'https://www.jianshu.com/p/' + item['slug']
    title = item['title']
    print(articleUrl)
    print(title)
    break
